name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Actualiza a la versión v4 para Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4  # Actualiza a la versión v4 para Node.js 20
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller --onefile --windowed main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3  # Asegúrate de usar una versión compatible con Node.js 20
      with:
        name: executable
        path: dist/
